type Profile {
  id: ID!
  imageUrl: String
  filename: String
  mimetype: String
  encoding: String
  bio: String
  userId: ID!
  createdAt: String!
  updatedAt: String!
}

type Query {
  profiles: [Profile!]!
  profile: Profile!
}

type Mutation {
  singleUpload(file: Upload!, id: ID!): Profile,
}

input ProfileInput {
  bio: String!
}

