type Profile {
  id: ID!
  imageUrl: String
  filename: String
  mimetype: String
  encoding: String
  bio: String!
  userId: User!
  createdAt: String!
  updatedAt: String!
}

type Mutation {
  singleUpload(file: Upload!, id: ID!): Profile,
}

input ProfileInput {
  bio: String!
}

