type Workspace {
  id: ID!
  title: String!
  ownerId: ID!
  createdAt: String!
  updatedAt: String!
  users: [User]
  owner: User
  workspaces_permissions: [User_Permissions]
}

type User_Workspaces {
  userId: ID!
  workspaceId: ID!
}


type Query {
  workspaces: [Workspace!]!
  workspaceMember: [Workspace!]!
  workspace(id: ID!): Workspace!
  usersWorkspace(id: ID!): [User]
}

type Mutation {
  createWorkspace(title: String!): Workspace!
  addUserToWorkspace(workspaceId: ID!, userId: ID!): User_Workspaces!
  removeUserFromWorkspace(workspaceId: ID!, userId: ID!): Boolean
}
