version: "3"
services:
  redis:
    image: redis
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - ${PORT}:4000
    command: npm run dev
    volumes:
      - .:/usr/app
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    depends_on:
      - db
      - redis
