type Permission {
  id: ID!
  name: String!
  createdAt: String!
  updatedAt: String!
  permissions_users: [User]
}

type User_Permissions {
  id: ID!
  userId: ID!
  permissionId: ID!
  workspaceId: ID!
  permissions_workspace: Workspace
  user_permission: User
}

type Query {
  userPermissionsByWorkspace(workspaceId: ID!): [User_Permissions]
  usersPermissionsByWorkspace(workspaceId: ID!): [Permission]
  showPermissions: [Permission]
}

type Mutation {
  addUserPermission(permissionId: ID!, userId: ID!, workspaceId: ID!): User_Permissions!
  removeUserPermission(permissionId: ID!, userId: ID!, workspaceId: ID!): Boolean
}
