type Task {
  id: ID!
  title: String!
  workspaceId: ID!
  link: String
  file: String
  description: String!
  filename: String
  mimetype: String
  encoding: String
  progress: String
  maxDate: String
  createdAt: String!
  updatedAt: String!
  priority: String
  assignTo: ID!
  tasksUsers: User
}

type Query {
  tasks(workspaceId: ID!): [Task!]!
}

type Mutation {
  createTask(
    title: String!
    workspaceId: ID!
    link: String
    maxDate: String
    description: String!
    priority: String
    assignTo: ID!
  ): Task!
  updateTask(
    id: ID!
    title: String!
    workspaceId: ID!
    link: String
    maxDate: String
    description: String!
    priority: String
    progress: String
    assignTo: ID!
  ): Task!
  deleteTask(id: ID!, workspaceId: ID!): Boolean
  taskSingleUpload(id: ID!, file: Upload!, workspaceId: ID!): Task,
}
