type Task {
  id: ID!
  title: String!
  workspaceId: ID!
  link: String
  file: String
  description: String!
  filename: String
  mimetype: String
  encoding: String
  progress: String
  maxDate: String
  createdAt: String!
  updatedAt: String!
}

type Query {
  tasks(workspaceId: ID!): [Task!]!
}

type Mutation {
  createTask(
    title: String!
    workspaceId: ID!
    link: String
    maxDate: String
    description: String!
  ): Task!
}
