type Comment {
  id: ID!
  body: String!
  createdAt: String!
  updatedAt: String!
  userId: ID!
  taskId: ID!
  author: User
  comment_task: Task
}

type Query {
  commentsByTask(taskId: ID!, workspaceId: ID!): [Comment]!
}

type Mutation {
  createComment(workspaceId: ID!, taskId: ID!, body: String!): Comment!
}

type Subscription {
  addComment(taskId: ID!): SubscriptionData!
}

type SubscriptionData {
  comment: Comment!
  author: User!
}