type User {
  id: ID!
  name: String!
  email: String!
  password: String!
  token: String,
  passwordResetToken: String
  passwordResetExpires: String
  emailConfirmationToken: String
  emailConfirmationExpires: String
  isVerified: Boolean
  createdAt: String!
}

input UserInput {
  name: String!
  email: String!
  password: String!
}

type Query {
  users: [User!]!
  user(id: ID!): User!
}

type Mutation {
  userRegister(data: UserInput!): User!
  userConfirmAccount(emailConfirmationToken: String!): User!
  userLogin(email: String!, password: String!): User!
  userForgotPassword(email: String!): User!
  userResetPassword(passwordResetToken: String!, password: String!): User!
}