type User {
  id: ID!
  firstName: String!
  lastName: String!
  email: String!
  password: String!
  token: String,
  passwordResetToken: String
  passwordResetExpires: String
  emailConfirmationToken: String
  emailConfirmationExpires: String
  isVerified: Boolean
  createdAt: String!
  users_tasks: Task
  profile: Profile
  users_permissions: [Permission]
  users_workspaces: Workspace
  usersWorkspaces: [Workspace]
}

type Query {
  users(query: String): [User!]!
  user: User!
  tasksByUser(workspaceId: ID!): [User!]!
}

type Mutation {
  userRegister(
    firstName: String!
    lastName: String!
    email: String!
    password: String!): User!
  userConfirmAccount(emailConfirmationToken: String!): User!
  userLogin(email: String!, password: String!): User!
  userForgotPassword(email: String!): User!
  userResetPassword(passwordResetToken: String!, password: String!): User!
  userLogout: Boolean
}